name: 'Docker Build'
description: 'Build Docker image with optional push (unified action for test and production builds)'

inputs:
  # Build options
  target:
    description: 'Docker build target (e.g., test, final)'
    required: false
    default: 'final'
  dockerfile:
    description: 'Dockerfile path'
    required: false
    default: 'Dockerfile'
  build-args:
    description: 'Build arguments (multiline KEY=VALUE)'
    required: false
    default: ''

  # Push options
  push:
    description: 'Push image to registry'
    required: false
    default: 'false'
  registry:
    description: 'Registry URL (required if push=true)'
    required: false
    default: ''
  repository:
    description: 'Repository name (required if push=true)'
    required: false
    default: ''
  image-tag:
    description: 'Image tag (required if push=true)'
    required: false
    default: ''
  extra-tags:
    description: 'Extra tags (newline separated)'
    required: false
    default: ''

  # Maven settings
  maven-settings-path:
    description: 'Path to Maven settings.xml (Docker secret)'
    required: false
    default: ''

outputs:
  image-uri:
    description: 'Full image URI (if pushed)'
    value: ${{ steps.output.outputs.uri }}
  digest:
    description: 'Image digest (if pushed)'
    value: ${{ steps.build.outputs.digest }}

runs:
  using: 'composite'
  steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Prepare Maven secret
      id: maven-secret
      shell: bash
      run: |
        if [ -n "${{ inputs.maven-settings-path }}" ] && [ -f "${{ inputs.maven-settings-path }}" ]; then
          cp "${{ inputs.maven-settings-path }}" .maven-settings.xml
          echo "path=.maven-settings.xml" >> $GITHUB_OUTPUT
          echo "has_maven=true" >> $GITHUB_OUTPUT
        else
          echo "has_maven=false" >> $GITHUB_OUTPUT
        fi

    - name: Build tags
      id: tags
      if: inputs.push == 'true'
      shell: bash
      run: |
        BASE="${{ inputs.registry }}/${{ inputs.repository }}"
        TAGS="${BASE}:${{ inputs.image-tag }}"
        if [ -n "${{ inputs.extra-tags }}" ]; then
          while IFS= read -r tag; do
            [ -n "$tag" ] && TAGS="${TAGS},${BASE}:${tag}"
          done <<< "${{ inputs.extra-tags }}"
        fi
        echo "tags=$TAGS" >> $GITHUB_OUTPUT

    - name: Build and push
      id: build
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        target: ${{ inputs.target }}
        push: ${{ inputs.push }}
        tags: ${{ inputs.push == 'true' && steps.tags.outputs.tags || '' }}
        build-args: ${{ inputs.build-args }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        secret-files: ${{ steps.maven-secret.outputs.has_maven == 'true' && format('maven_settings={0}', steps.maven-secret.outputs.path) || '' }}

    - name: Output URI
      id: output
      if: inputs.push == 'true'
      shell: bash
      run: |
        echo "uri=${{ inputs.registry }}/${{ inputs.repository }}:${{ inputs.image-tag }}" >> $GITHUB_OUTPUT

    - name: Cleanup
      if: always()
      shell: bash
      run: rm -f .maven-settings.xml
