name: 'ECS Restart'
description: 'Force restart an ECS service without changing the image'

inputs:
  aws-role:
    description: 'AWS IAM Role ARN for OIDC'
    required: true
  aws-region:
    description: 'AWS Region'
    required: false
    default: 'eu-west-1'
  cluster-name:
    description: 'ECS Cluster name'
    required: true
  service-name:
    description: 'ECS Service name'
    required: true
  wait:
    description: 'Wait for stability'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role }}
        aws-region: ${{ inputs.aws-region }}

    - name: Force restart
      shell: bash
      run: |
        echo "Restarting ${{ inputs.service-name }} on ${{ inputs.cluster-name }}..."
        aws ecs update-service \
          --cluster "${{ inputs.cluster-name }}" \
          --service "${{ inputs.service-name }}" \
          --force-new-deployment > /dev/null
        echo "Restart triggered"

    - name: Wait for stability
      if: inputs.wait == 'true'
      shell: bash
      run: |
        echo "Waiting for service stability..."
        aws ecs wait services-stable \
          --cluster "${{ inputs.cluster-name }}" \
          --services "${{ inputs.service-name }}"
        echo "Service stable"
